[package]
edition = "2024"
name = "rpctest"
version = "0.1.0"
authors = ["Yannis Wagner <yannis.wagner@hhu.de>"]

[lib]
crate-type = ["staticlib"]
path = "src/rpctest.rs"
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
runtime = { path = "../../library/runtime" }
terminal = { path = "../../library/terminal" }
concurrent = { path = "../../library/concurrent" }
spin = "0.9"
capnp = { version = "0.13", default-features = false }
rpc = { path = "../../library/rpc" }
naming = { path = "../../library/naming" }
syscall = { path = "../../library/syscall" }

[build-dependencies]
capnpc = "0.13"